### ISSUE TITLE
XQuartz/rgl Requirements

### ISSUE THREAD

**Issue by atroiano** [luca-scr/msir#1]
For whatever reason, this packages requires XQuartz and rgl to work.  I was able to copy and paste the raw code from the github repo and run the loess.sd function without any issues.   I am not able to get rgl or XQuartz working on the VM I am using.   I don't know if those are needed but they don't seem necessary given it works without any special software installed locally.  I have never written an R package so maybe I am missing something.

**Comment by luca-scr** [comment]
Package **rgl** is needed if you want to use the `spinplot()` function. However, I agree with you that it is too strong to declare it as Imports.
I have moved the package from the list of Imports to the list if Suggests. This will fix your issue.
Please update from current GitHub version using
```{r}
devtools::install_github("luca-scr/msir", build_vignettes = TRUE)
```

**Comment by atroiano** [comment]
Cheers
